displayName=Discord Multi Webhook Notifier
author=Moseph
support==https://github.com/malkailany/osrs-discord-multi-webhook-plugin.git
description=Sends notifications to multiple Discord webhooks for various in-game events with customizable settings
tags=discord,webhook,notification,collection,log,pet,level,drop,quest,death,notification,loot,screenshot
plugins=com.moseph.discordmultiwebhook.DiscordMultiWebhookPlugin